# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Transformers
author: Antal van den Bosch, Lisa Bylinina, Yupei Du, Yingjin Song
logo: images/antalb_looking_over_the_shoulder_of_a_transformer_robot_reading_84cc821f-a71d-4935-9a2d-cb33114959b7.png

sphinx:
  recursive_update: true
  config:
    html_theme_options:
      repository_provider: github
      show_toc_level: 2
    html_sidebars:
      "**": ["navbar-logo.html", "search-field.html", "sbt-sidebar-nav.html"]

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: infomtalc.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://antalvdb.github.io/  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
